%% Generate C source files from .dbc with cantools in the venv
% python -m cantools generate_c_source --use-float --database-name cmmc can_messages_mini_celka.dbc

database_name = 'cmmc';
dbc_file = 'test.dbc';

% Call the cantools from the venv
system(['"', fullfile(pwd, 'venv', 'Scripts', 'python.exe'), '" -m cantools generate_c_source --use-float --database-name ' database_name ' ' dbc_file]);

% Move generated files into src/
movefile([database_name '.c'], 'src');
movefile([database_name '.h'], 'src');


%% Generate code from template_decoder.c and name it %database_name%_decoder.c

%where should i obtain the values to fill?

%what values i want to fill

% I want to obtain something like that after all
% decoded = struct( ...
%     'frame_name', 'MSG1', ...
%     'frame_id', uint32(0x20), ...
%     'frame_length', uint8(8), ...
%     'signals', struct( ...
%         'speed', 12.3, ...
%         'acceleration', 4.5, ...
%         'distance', 100, ...
%         'status', 1 ...
%     ) ...
% );