/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Sun Apr 26 12:49:19 2026.
 */

#include <string.h>

#include "cmmc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int cmmc_odrive_heartbeat_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_heartbeat_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->axis_error, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->axis_error, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->axis_error, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->axis_error, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->axis_current_state, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->motor_error_flag, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->encoder_error_flag, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->controller_error_flag, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->trajectory_done_flag, 7u, 0x80u);

    return (8);
}

int cmmc_odrive_heartbeat_unpack(
    struct cmmc_odrive_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->axis_error = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->axis_error |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->axis_error |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->axis_error |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->axis_current_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->motor_error_flag = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->encoder_error_flag = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->controller_error_flag = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->trajectory_done_flag = unpack_right_shift_u8(src_p[5], 7u, 0x80u);

    return (0);
}

int cmmc_odrive_heartbeat_init(struct cmmc_odrive_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_odrive_heartbeat_t));

    return 0;
}

uint32_t cmmc_odrive_heartbeat_axis_error_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_heartbeat_axis_error_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_heartbeat_axis_error_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_odrive_heartbeat_axis_current_state_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_odrive_heartbeat_axis_current_state_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_odrive_heartbeat_axis_current_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_odrive_heartbeat_motor_error_flag_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_odrive_heartbeat_motor_error_flag_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_odrive_heartbeat_motor_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t cmmc_odrive_heartbeat_encoder_error_flag_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_odrive_heartbeat_encoder_error_flag_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_odrive_heartbeat_encoder_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t cmmc_odrive_heartbeat_controller_error_flag_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_odrive_heartbeat_controller_error_flag_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_odrive_heartbeat_controller_error_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t cmmc_odrive_heartbeat_trajectory_done_flag_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_odrive_heartbeat_trajectory_done_flag_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_odrive_heartbeat_trajectory_done_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int cmmc_odrive_set_requested_state_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_set_requested_state_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->axis_requested_state, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->axis_requested_state, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->axis_requested_state, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->axis_requested_state, 24u, 0xffu);

    return (4);
}

int cmmc_odrive_set_requested_state_unpack(
    struct cmmc_odrive_set_requested_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->axis_requested_state = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->axis_requested_state |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->axis_requested_state |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->axis_requested_state |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

int cmmc_odrive_set_requested_state_init(struct cmmc_odrive_set_requested_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_odrive_set_requested_state_t));

    return 0;
}

uint32_t cmmc_odrive_set_requested_state_axis_requested_state_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_set_requested_state_axis_requested_state_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_set_requested_state_axis_requested_state_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int cmmc_odrive_set_input_vel_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_set_input_vel_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->input_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->input_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->input_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->input_vel, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->torque_ff, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->torque_ff, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->torque_ff, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->torque_ff, 24u, 0xffu);

    return (8);
}

int cmmc_odrive_set_input_vel_unpack(
    struct cmmc_odrive_set_input_vel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->input_vel = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->input_vel |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->input_vel |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->input_vel |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->torque_ff = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->torque_ff |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->torque_ff |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->torque_ff |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int cmmc_odrive_set_input_vel_init(struct cmmc_odrive_set_input_vel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_odrive_set_input_vel_t));

    return 0;
}

uint32_t cmmc_odrive_set_input_vel_input_vel_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_set_input_vel_input_vel_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_set_input_vel_input_vel_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t cmmc_odrive_set_input_vel_torque_ff_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_set_input_vel_torque_ff_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_set_input_vel_torque_ff_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int cmmc_odrive_get_iq_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_get_iq_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->iq_setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->iq_setpoint, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->iq_setpoint, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->iq_setpoint, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->iq_measured, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->iq_measured, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->iq_measured, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->iq_measured, 24u, 0xffu);

    return (8);
}

int cmmc_odrive_get_iq_unpack(
    struct cmmc_odrive_get_iq_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->iq_setpoint = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->iq_setpoint |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->iq_setpoint |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->iq_setpoint |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->iq_measured = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->iq_measured |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->iq_measured |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->iq_measured |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int cmmc_odrive_get_iq_init(struct cmmc_odrive_get_iq_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_odrive_get_iq_t));

    return 0;
}

uint32_t cmmc_odrive_get_iq_iq_setpoint_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_get_iq_iq_setpoint_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_get_iq_iq_setpoint_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t cmmc_odrive_get_iq_iq_measured_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_get_iq_iq_measured_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_get_iq_iq_measured_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int cmmc_odrive_get_sensorless_estimates_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_get_sensorless_estimates_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->sensorless_pos_estimate, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->sensorless_pos_estimate, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->sensorless_pos_estimate, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->sensorless_pos_estimate, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->sensorless_vel_estimate, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->sensorless_vel_estimate, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->sensorless_vel_estimate, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->sensorless_vel_estimate, 24u, 0xffu);

    return (8);
}

int cmmc_odrive_get_sensorless_estimates_unpack(
    struct cmmc_odrive_get_sensorless_estimates_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->sensorless_pos_estimate = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->sensorless_pos_estimate |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->sensorless_pos_estimate |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->sensorless_pos_estimate |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->sensorless_vel_estimate = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->sensorless_vel_estimate |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->sensorless_vel_estimate |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->sensorless_vel_estimate |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int cmmc_odrive_get_sensorless_estimates_init(struct cmmc_odrive_get_sensorless_estimates_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_odrive_get_sensorless_estimates_t));

    return 0;
}

uint32_t cmmc_odrive_get_sensorless_estimates_sensorless_pos_estimate_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_get_sensorless_estimates_sensorless_pos_estimate_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_get_sensorless_estimates_sensorless_pos_estimate_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t cmmc_odrive_get_sensorless_estimates_sensorless_vel_estimate_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_get_sensorless_estimates_sensorless_vel_estimate_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_get_sensorless_estimates_sensorless_vel_estimate_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int cmmc_odrive_get_bus_voltage_current_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_get_bus_voltage_current_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->bus_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->bus_voltage, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->bus_voltage, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->bus_voltage, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->bus_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->bus_current, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->bus_current, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->bus_current, 24u, 0xffu);

    return (8);
}

int cmmc_odrive_get_bus_voltage_current_unpack(
    struct cmmc_odrive_get_bus_voltage_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bus_voltage = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->bus_voltage |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->bus_voltage |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->bus_voltage |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->bus_current = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->bus_current |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->bus_current |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->bus_current |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int cmmc_odrive_get_bus_voltage_current_init(struct cmmc_odrive_get_bus_voltage_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_odrive_get_bus_voltage_current_t));

    return 0;
}

uint32_t cmmc_odrive_get_bus_voltage_current_bus_voltage_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_get_bus_voltage_current_bus_voltage_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_get_bus_voltage_current_bus_voltage_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t cmmc_odrive_get_bus_voltage_current_bus_current_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_odrive_get_bus_voltage_current_bus_current_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_odrive_get_bus_voltage_current_bus_current_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int cmmc_odrive_clear_errors_pack(
    uint8_t *dst_p,
    const struct cmmc_odrive_clear_errors_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int cmmc_odrive_clear_errors_unpack(
    struct cmmc_odrive_clear_errors_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int cmmc_radio_control_pack(
    uint8_t *dst_p,
    const struct cmmc_radio_control_t *src_p,
    size_t size)
{
    uint16_t front_pitch;
    uint16_t front_roll;
    uint16_t rear_pitch;
    uint16_t steering;
    uint16_t throttle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    throttle = (uint16_t)src_p->throttle;
    dst_p[0] |= pack_left_shift_u16(throttle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(throttle, 8u, 0x07u);
    steering = (uint16_t)src_p->steering;
    dst_p[1] |= pack_left_shift_u16(steering, 3u, 0xf8u);
    dst_p[2] |= pack_right_shift_u16(steering, 5u, 0x3fu);
    front_pitch = (uint16_t)src_p->front_pitch;
    dst_p[2] |= pack_left_shift_u16(front_pitch, 6u, 0xc0u);
    dst_p[3] |= pack_right_shift_u16(front_pitch, 2u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(front_pitch, 10u, 0x01u);
    front_roll = (uint16_t)src_p->front_roll;
    dst_p[4] |= pack_left_shift_u16(front_roll, 1u, 0xfeu);
    dst_p[5] |= pack_right_shift_u16(front_roll, 7u, 0x0fu);
    rear_pitch = (uint16_t)src_p->rear_pitch;
    dst_p[5] |= pack_left_shift_u16(rear_pitch, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u16(rear_pitch, 4u, 0x7fu);
    dst_p[7] |= pack_left_shift_u8(src_p->free_bits, 0u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->sync_switch, 2u, 0x0cu);
    dst_p[7] |= pack_left_shift_u8(src_p->arm_switch, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->mode_switch, 6u, 0xc0u);

    return (8);
}

int cmmc_radio_control_unpack(
    struct cmmc_radio_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_pitch;
    uint16_t front_roll;
    uint16_t rear_pitch;
    uint16_t steering;
    uint16_t throttle;

    if (size < 8u) {
        return (-EINVAL);
    }

    throttle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    throttle |= unpack_left_shift_u16(src_p[1], 8u, 0x07u);

    if ((throttle & (1u << 10)) != 0u) {
        throttle |= 0xf800u;
    }

    dst_p->throttle = (int16_t)throttle;
    steering = unpack_right_shift_u16(src_p[1], 3u, 0xf8u);
    steering |= unpack_left_shift_u16(src_p[2], 5u, 0x3fu);

    if ((steering & (1u << 10)) != 0u) {
        steering |= 0xf800u;
    }

    dst_p->steering = (int16_t)steering;
    front_pitch = unpack_right_shift_u16(src_p[2], 6u, 0xc0u);
    front_pitch |= unpack_left_shift_u16(src_p[3], 2u, 0xffu);
    front_pitch |= unpack_left_shift_u16(src_p[4], 10u, 0x01u);

    if ((front_pitch & (1u << 10)) != 0u) {
        front_pitch |= 0xf800u;
    }

    dst_p->front_pitch = (int16_t)front_pitch;
    front_roll = unpack_right_shift_u16(src_p[4], 1u, 0xfeu);
    front_roll |= unpack_left_shift_u16(src_p[5], 7u, 0x0fu);

    if ((front_roll & (1u << 10)) != 0u) {
        front_roll |= 0xf800u;
    }

    dst_p->front_roll = (int16_t)front_roll;
    rear_pitch = unpack_right_shift_u16(src_p[5], 4u, 0xf0u);
    rear_pitch |= unpack_left_shift_u16(src_p[6], 4u, 0x7fu);

    if ((rear_pitch & (1u << 10)) != 0u) {
        rear_pitch |= 0xf800u;
    }

    dst_p->rear_pitch = (int16_t)rear_pitch;
    dst_p->free_bits = unpack_right_shift_u8(src_p[7], 0u, 0x03u);
    dst_p->sync_switch = unpack_right_shift_u8(src_p[7], 2u, 0x0cu);
    dst_p->arm_switch = unpack_right_shift_u8(src_p[7], 4u, 0x30u);
    dst_p->mode_switch = unpack_right_shift_u8(src_p[7], 6u, 0xc0u);

    return (0);
}

int cmmc_radio_control_init(struct cmmc_radio_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_radio_control_t));

    return 0;
}

int16_t cmmc_radio_control_throttle_encode(float value)
{
    return (int16_t)(value);
}

float cmmc_radio_control_throttle_decode(int16_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_throttle_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

int16_t cmmc_radio_control_steering_encode(float value)
{
    return (int16_t)(value);
}

float cmmc_radio_control_steering_decode(int16_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_steering_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

int16_t cmmc_radio_control_front_pitch_encode(float value)
{
    return (int16_t)(value);
}

float cmmc_radio_control_front_pitch_decode(int16_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_front_pitch_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

int16_t cmmc_radio_control_front_roll_encode(float value)
{
    return (int16_t)(value);
}

float cmmc_radio_control_front_roll_decode(int16_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_front_roll_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

int16_t cmmc_radio_control_rear_pitch_encode(float value)
{
    return (int16_t)(value);
}

float cmmc_radio_control_rear_pitch_decode(int16_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_rear_pitch_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1000));
}

uint8_t cmmc_radio_control_free_bits_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_radio_control_free_bits_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_free_bits_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t cmmc_radio_control_sync_switch_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_radio_control_sync_switch_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_sync_switch_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t cmmc_radio_control_arm_switch_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_radio_control_arm_switch_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_arm_switch_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t cmmc_radio_control_mode_switch_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_radio_control_mode_switch_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_radio_control_mode_switch_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int cmmc_auto_control_pack(
    uint8_t *dst_p,
    const struct cmmc_auto_control_t *src_p,
    size_t size)
{
    uint16_t front_left_setpoint;
    uint16_t front_right_setpoint;
    uint16_t rear_setpoint;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    front_left_setpoint = (uint16_t)src_p->front_left_setpoint;
    dst_p[0] |= pack_left_shift_u16(front_left_setpoint, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(front_left_setpoint, 8u, 0x0fu);
    front_right_setpoint = (uint16_t)src_p->front_right_setpoint;
    dst_p[1] |= pack_left_shift_u16(front_right_setpoint, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(front_right_setpoint, 4u, 0xffu);
    rear_setpoint = (uint16_t)src_p->rear_setpoint;
    dst_p[3] |= pack_left_shift_u16(rear_setpoint, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(rear_setpoint, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->padding, 4u, 0x30u);

    return (5);
}

int cmmc_auto_control_unpack(
    struct cmmc_auto_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_left_setpoint;
    uint16_t front_right_setpoint;
    uint16_t rear_setpoint;

    if (size < 5u) {
        return (-EINVAL);
    }

    front_left_setpoint = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    front_left_setpoint |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);

    if ((front_left_setpoint & (1u << 11)) != 0u) {
        front_left_setpoint |= 0xf000u;
    }

    dst_p->front_left_setpoint = (int16_t)front_left_setpoint;
    front_right_setpoint = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    front_right_setpoint |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);

    if ((front_right_setpoint & (1u << 11)) != 0u) {
        front_right_setpoint |= 0xf000u;
    }

    dst_p->front_right_setpoint = (int16_t)front_right_setpoint;
    rear_setpoint = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    rear_setpoint |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);

    if ((rear_setpoint & (1u << 11)) != 0u) {
        rear_setpoint |= 0xf000u;
    }

    dst_p->rear_setpoint = (int16_t)rear_setpoint;
    dst_p->padding = unpack_right_shift_u8(src_p[4], 4u, 0x30u);

    return (0);
}

int cmmc_auto_control_init(struct cmmc_auto_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_auto_control_t));

    return 0;
}

int16_t cmmc_auto_control_front_left_setpoint_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float cmmc_auto_control_front_left_setpoint_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool cmmc_auto_control_front_left_setpoint_is_in_range(int16_t value)
{
    return ((value >= -600) && (value <= 1200));
}

int16_t cmmc_auto_control_front_right_setpoint_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float cmmc_auto_control_front_right_setpoint_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool cmmc_auto_control_front_right_setpoint_is_in_range(int16_t value)
{
    return ((value >= -600) && (value <= 1200));
}

int16_t cmmc_auto_control_rear_setpoint_encode(float value)
{
    return (int16_t)(value / 0.01f);
}

float cmmc_auto_control_rear_setpoint_decode(int16_t value)
{
    return ((float)value * 0.01f);
}

bool cmmc_auto_control_rear_setpoint_is_in_range(int16_t value)
{
    return ((value >= -600) && (value <= 1200));
}

uint8_t cmmc_auto_control_padding_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_auto_control_padding_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_auto_control_padding_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int cmmc_accelerometer_pack(
    uint8_t *dst_p,
    const struct cmmc_accelerometer_t *src_p,
    size_t size)
{
    uint16_t ax;
    uint16_t ay;
    uint16_t az;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    ax = (uint16_t)src_p->ax;
    dst_p[0] |= pack_left_shift_u16(ax, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(ax, 8u, 0xffu);
    ay = (uint16_t)src_p->ay;
    dst_p[2] |= pack_left_shift_u16(ay, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(ay, 8u, 0xffu);
    az = (uint16_t)src_p->az;
    dst_p[4] |= pack_left_shift_u16(az, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(az, 8u, 0xffu);

    return (6);
}

int cmmc_accelerometer_unpack(
    struct cmmc_accelerometer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t ax;
    uint16_t ay;
    uint16_t az;

    if (size < 6u) {
        return (-EINVAL);
    }

    ax = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    ax |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->ax = (int16_t)ax;
    ay = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    ay |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->ay = (int16_t)ay;
    az = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    az |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->az = (int16_t)az;

    return (0);
}

int cmmc_accelerometer_init(struct cmmc_accelerometer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_accelerometer_t));

    return 0;
}

int16_t cmmc_accelerometer_ax_encode(float value)
{
    return (int16_t)(value / 6.1035e-05f);
}

float cmmc_accelerometer_ax_decode(int16_t value)
{
    return ((float)value * 6.1035e-05f);
}

bool cmmc_accelerometer_ax_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t cmmc_accelerometer_ay_encode(float value)
{
    return (int16_t)(value / 6.1035e-05f);
}

float cmmc_accelerometer_ay_decode(int16_t value)
{
    return ((float)value * 6.1035e-05f);
}

bool cmmc_accelerometer_ay_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t cmmc_accelerometer_az_encode(float value)
{
    return (int16_t)(value / 6.1035e-05f);
}

float cmmc_accelerometer_az_decode(int16_t value)
{
    return ((float)value * 6.1035e-05f);
}

bool cmmc_accelerometer_az_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int cmmc_gyroscope_pack(
    uint8_t *dst_p,
    const struct cmmc_gyroscope_t *src_p,
    size_t size)
{
    uint16_t gx;
    uint16_t gy;
    uint16_t gz;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gx = (uint16_t)src_p->gx;
    dst_p[0] |= pack_left_shift_u16(gx, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gx, 8u, 0xffu);
    gy = (uint16_t)src_p->gy;
    dst_p[2] |= pack_left_shift_u16(gy, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gy, 8u, 0xffu);
    gz = (uint16_t)src_p->gz;
    dst_p[4] |= pack_left_shift_u16(gz, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gz, 8u, 0xffu);

    return (6);
}

int cmmc_gyroscope_unpack(
    struct cmmc_gyroscope_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gx;
    uint16_t gy;
    uint16_t gz;

    if (size < 6u) {
        return (-EINVAL);
    }

    gx = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gx |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gx = (int16_t)gx;
    gy = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gy |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gy = (int16_t)gy;
    gz = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gz |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gz = (int16_t)gz;

    return (0);
}

int cmmc_gyroscope_init(struct cmmc_gyroscope_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_gyroscope_t));

    return 0;
}

int16_t cmmc_gyroscope_gx_encode(float value)
{
    return (int16_t)(value / 0.0609756f);
}

float cmmc_gyroscope_gx_decode(int16_t value)
{
    return ((float)value * 0.0609756f);
}

bool cmmc_gyroscope_gx_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t cmmc_gyroscope_gy_encode(float value)
{
    return (int16_t)(value / 0.0609756f);
}

float cmmc_gyroscope_gy_decode(int16_t value)
{
    return ((float)value * 0.0609756f);
}

bool cmmc_gyroscope_gy_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t cmmc_gyroscope_gz_encode(float value)
{
    return (int16_t)(value / 0.0609756f);
}

float cmmc_gyroscope_gz_decode(int16_t value)
{
    return ((float)value * 0.0609756f);
}

bool cmmc_gyroscope_gz_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int cmmc_gps_motion_pack(
    uint8_t *dst_p,
    const struct cmmc_gps_motion_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ground_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ground_speed, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->heading, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->heading, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->heading, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->heading, 24u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->speed_accuracy_estimate, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->speed_accuracy_estimate, 6u, 0x0fu);
    dst_p[6] |= pack_left_shift_u16(src_p->heading_accuracy_estimate, 4u, 0xf0u);
    dst_p[7] |= pack_right_shift_u16(src_p->heading_accuracy_estimate, 4u, 0xffu);

    return (8);
}

int cmmc_gps_motion_unpack(
    struct cmmc_gps_motion_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ground_speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ground_speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->heading = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->heading |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->heading |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->heading |= unpack_left_shift_u32(src_p[5], 24u, 0x03u);
    dst_p->speed_accuracy_estimate = unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->speed_accuracy_estimate |= unpack_left_shift_u16(src_p[6], 6u, 0x0fu);
    dst_p->heading_accuracy_estimate = unpack_right_shift_u16(src_p[6], 4u, 0xf0u);
    dst_p->heading_accuracy_estimate |= unpack_left_shift_u16(src_p[7], 4u, 0xffu);

    return (0);
}

int cmmc_gps_motion_init(struct cmmc_gps_motion_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_gps_motion_t));

    return 0;
}

uint16_t cmmc_gps_motion_ground_speed_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float cmmc_gps_motion_ground_speed_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool cmmc_gps_motion_ground_speed_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint32_t cmmc_gps_motion_heading_encode(float value)
{
    return (uint32_t)(value / 1e-05f);
}

float cmmc_gps_motion_heading_decode(uint32_t value)
{
    return ((float)value * 1e-05f);
}

bool cmmc_gps_motion_heading_is_in_range(uint32_t value)
{
    return (value <= 36000000u);
}

uint16_t cmmc_gps_motion_speed_accuracy_estimate_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float cmmc_gps_motion_speed_accuracy_estimate_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool cmmc_gps_motion_speed_accuracy_estimate_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint16_t cmmc_gps_motion_heading_accuracy_estimate_encode(float value)
{
    return (uint16_t)(value / 0.01f);
}

float cmmc_gps_motion_heading_accuracy_estimate_decode(uint16_t value)
{
    return ((float)value * 0.01f);
}

bool cmmc_gps_motion_heading_accuracy_estimate_is_in_range(uint16_t value)
{
    return (value <= 2500u);
}

int cmmc_gps_position_pack(
    uint8_t *dst_p,
    const struct cmmc_gps_position_t *src_p,
    size_t size)
{
    uint32_t latitude;
    uint32_t longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    latitude = (uint32_t)src_p->latitude;
    dst_p[0] |= pack_left_shift_u32(latitude, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(latitude, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(latitude, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(latitude, 24u, 0xffu);
    longitude = (uint32_t)src_p->longitude;
    dst_p[4] |= pack_left_shift_u32(longitude, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(longitude, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(longitude, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(longitude, 24u, 0xffu);

    return (8);
}

int cmmc_gps_position_unpack(
    struct cmmc_gps_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t latitude;
    uint32_t longitude;

    if (size < 8u) {
        return (-EINVAL);
    }

    latitude = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    latitude |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->latitude = (int32_t)latitude;
    longitude = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    longitude |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->longitude = (int32_t)longitude;

    return (0);
}

int cmmc_gps_position_init(struct cmmc_gps_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_gps_position_t));

    return 0;
}

int32_t cmmc_gps_position_latitude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float cmmc_gps_position_latitude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool cmmc_gps_position_latitude_is_in_range(int32_t value)
{
    return ((value >= -900000000) && (value <= 900000000));
}

int32_t cmmc_gps_position_longitude_encode(float value)
{
    return (int32_t)(value / 1e-07f);
}

float cmmc_gps_position_longitude_decode(int32_t value)
{
    return ((float)value * 1e-07f);
}

bool cmmc_gps_position_longitude_is_in_range(int32_t value)
{
    return ((value >= -1800000000) && (value <= 1800000000));
}

int cmmc_gps_time_status_pack(
    uint8_t *dst_p,
    const struct cmmc_gps_time_status_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->year, 0u, 0x3fu);
    dst_p[0] |= pack_left_shift_u8(src_p->month, 6u, 0xc0u);
    dst_p[1] |= pack_right_shift_u8(src_p->month, 2u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->day, 2u, 0x7cu);
    dst_p[1] |= pack_left_shift_u8(src_p->hour, 7u, 0x80u);
    dst_p[2] |= pack_right_shift_u8(src_p->hour, 1u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->min, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u8(src_p->min, 4u, 0x03u);
    dst_p[3] |= pack_left_shift_u8(src_p->sec, 2u, 0xfcu);
    dst_p[4] |= pack_left_shift_u8(src_p->valid, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->fix_type, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->num_sv, 0u, 0xffu);

    return (7);
}

int cmmc_gps_time_status_unpack(
    struct cmmc_gps_time_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->year = unpack_right_shift_u8(src_p[0], 0u, 0x3fu);
    dst_p->month = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->month |= unpack_left_shift_u8(src_p[1], 2u, 0x03u);
    dst_p->day = unpack_right_shift_u8(src_p[1], 2u, 0x7cu);
    dst_p->hour = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->hour |= unpack_left_shift_u8(src_p[2], 1u, 0x0fu);
    dst_p->min = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->min |= unpack_left_shift_u8(src_p[3], 4u, 0x03u);
    dst_p->sec = unpack_right_shift_u8(src_p[3], 2u, 0xfcu);
    dst_p->valid = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->fix_type = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->num_sv = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int cmmc_gps_time_status_init(struct cmmc_gps_time_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_gps_time_status_t));

    return 0;
}

uint8_t cmmc_gps_time_status_year_encode(float value)
{
    return (uint8_t)(value - 2020.0f);
}

float cmmc_gps_time_status_year_decode(uint8_t value)
{
    return ((float)value + 2020.0f);
}

bool cmmc_gps_time_status_year_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

uint8_t cmmc_gps_time_status_month_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_month_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_month_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 12u));
}

uint8_t cmmc_gps_time_status_day_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_day_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_day_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 31u));
}

uint8_t cmmc_gps_time_status_hour_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_hour_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_hour_is_in_range(uint8_t value)
{
    return (value <= 23u);
}

uint8_t cmmc_gps_time_status_min_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_min_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_min_is_in_range(uint8_t value)
{
    return (value <= 59u);
}

uint8_t cmmc_gps_time_status_sec_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_sec_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_sec_is_in_range(uint8_t value)
{
    return (value <= 60u);
}

uint8_t cmmc_gps_time_status_valid_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_valid_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_valid_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t cmmc_gps_time_status_fix_type_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_fix_type_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_fix_type_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

uint8_t cmmc_gps_time_status_num_sv_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_gps_time_status_num_sv_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_gps_time_status_num_sv_is_in_range(uint8_t value)
{
    return (value <= 50u);
}

int cmmc_actuator_configuration_pack(
    uint8_t *dst_p,
    const struct cmmc_actuator_configuration_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->request, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->actuator, 4u, 0xf0u);

    return (1);
}

int cmmc_actuator_configuration_unpack(
    struct cmmc_actuator_configuration_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->request = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->actuator = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);

    return (0);
}

int cmmc_actuator_configuration_init(struct cmmc_actuator_configuration_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_actuator_configuration_t));

    return 0;
}

uint8_t cmmc_actuator_configuration_request_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_actuator_configuration_request_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_actuator_configuration_request_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t cmmc_actuator_configuration_actuator_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_actuator_configuration_actuator_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_actuator_configuration_actuator_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int cmmc_actuator_right_foil_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_actuator_right_foil_feedback_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current = (uint16_t)src_p->current;
    dst_p[0] |= pack_left_shift_u16(current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->voltage, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage, 6u, 0x0fu);
    power = (uint8_t)src_p->power;
    dst_p[2] |= pack_left_shift_u8(power, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u8(power, 4u, 0x0fu);
    dst_p[3] |= pack_left_shift_u16(src_p->setpoint_us, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->setpoint_us, 4u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->position_raw, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->position_raw, 2u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->position_raw, 10u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->free_bits, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->free_bits, 6u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->mode, 4u, 0xf0u);

    return (8);
}

int cmmc_actuator_right_foil_feedback_unpack(
    struct cmmc_actuator_right_foil_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((current & (1u << 9)) != 0u) {
        current |= 0xfc00u;
    }

    dst_p->current = (int16_t)current;
    dst_p->voltage = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    power = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    power |= unpack_left_shift_u8(src_p[3], 4u, 0x0fu);
    dst_p->power = (int8_t)power;
    dst_p->setpoint_us = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->setpoint_us |= unpack_left_shift_u16(src_p[4], 4u, 0x3fu);
    dst_p->position_raw = unpack_right_shift_u16(src_p[4], 6u, 0xc0u);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[6], 10u, 0x03u);
    dst_p->free_bits = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->free_bits |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);
    dst_p->mode = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);

    return (0);
}

int cmmc_actuator_right_foil_feedback_init(struct cmmc_actuator_right_foil_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_actuator_right_foil_feedback_t));

    return 0;
}

int16_t cmmc_actuator_right_foil_feedback_current_encode(float value)
{
    return (int16_t)(value / 0.002f);
}

float cmmc_actuator_right_foil_feedback_current_decode(int16_t value)
{
    return ((float)value * 0.002f);
}

bool cmmc_actuator_right_foil_feedback_current_is_in_range(int16_t value)
{
    return ((value >= -500) && (value <= 500));
}

uint16_t cmmc_actuator_right_foil_feedback_voltage_encode(float value)
{
    return (uint16_t)((value - 3.6f) / 0.003f);
}

float cmmc_actuator_right_foil_feedback_voltage_decode(uint16_t value)
{
    return (((float)value * 0.003f) + 3.6f);
}

bool cmmc_actuator_right_foil_feedback_voltage_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

int8_t cmmc_actuator_right_foil_feedback_power_encode(float value)
{
    return (int8_t)(value / 0.05f);
}

float cmmc_actuator_right_foil_feedback_power_decode(int8_t value)
{
    return ((float)value * 0.05f);
}

bool cmmc_actuator_right_foil_feedback_power_is_in_range(int8_t value)
{
    return ((value >= -120) && (value <= 120));
}

uint16_t cmmc_actuator_right_foil_feedback_setpoint_us_encode(float value)
{
    return (uint16_t)(value - 988.0f);
}

float cmmc_actuator_right_foil_feedback_setpoint_us_decode(uint16_t value)
{
    return ((float)value + 988.0f);
}

bool cmmc_actuator_right_foil_feedback_setpoint_us_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t cmmc_actuator_right_foil_feedback_position_raw_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_right_foil_feedback_position_raw_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_right_foil_feedback_position_raw_is_in_range(uint16_t value)
{
    return (value <= 4091u);
}

uint16_t cmmc_actuator_right_foil_feedback_free_bits_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_right_foil_feedback_free_bits_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_right_foil_feedback_free_bits_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t cmmc_actuator_right_foil_feedback_mode_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_actuator_right_foil_feedback_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_actuator_right_foil_feedback_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int cmmc_actuator_left_foil_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_actuator_left_foil_feedback_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current = (uint16_t)src_p->current;
    dst_p[0] |= pack_left_shift_u16(current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->voltage, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage, 6u, 0x0fu);
    power = (uint8_t)src_p->power;
    dst_p[2] |= pack_left_shift_u8(power, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u8(power, 4u, 0x0fu);
    dst_p[3] |= pack_left_shift_u16(src_p->setpoint_us, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->setpoint_us, 4u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->position_raw, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->position_raw, 2u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->position_raw, 10u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->free_bits, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->free_bits, 6u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->mode, 4u, 0xf0u);

    return (8);
}

int cmmc_actuator_left_foil_feedback_unpack(
    struct cmmc_actuator_left_foil_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((current & (1u << 9)) != 0u) {
        current |= 0xfc00u;
    }

    dst_p->current = (int16_t)current;
    dst_p->voltage = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    power = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    power |= unpack_left_shift_u8(src_p[3], 4u, 0x0fu);
    dst_p->power = (int8_t)power;
    dst_p->setpoint_us = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->setpoint_us |= unpack_left_shift_u16(src_p[4], 4u, 0x3fu);
    dst_p->position_raw = unpack_right_shift_u16(src_p[4], 6u, 0xc0u);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[6], 10u, 0x03u);
    dst_p->free_bits = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->free_bits |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);
    dst_p->mode = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);

    return (0);
}

int cmmc_actuator_left_foil_feedback_init(struct cmmc_actuator_left_foil_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_actuator_left_foil_feedback_t));

    return 0;
}

int16_t cmmc_actuator_left_foil_feedback_current_encode(float value)
{
    return (int16_t)(value / 0.002f);
}

float cmmc_actuator_left_foil_feedback_current_decode(int16_t value)
{
    return ((float)value * 0.002f);
}

bool cmmc_actuator_left_foil_feedback_current_is_in_range(int16_t value)
{
    return ((value >= -500) && (value <= 500));
}

uint16_t cmmc_actuator_left_foil_feedback_voltage_encode(float value)
{
    return (uint16_t)((value - 3.6f) / 0.003f);
}

float cmmc_actuator_left_foil_feedback_voltage_decode(uint16_t value)
{
    return (((float)value * 0.003f) + 3.6f);
}

bool cmmc_actuator_left_foil_feedback_voltage_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

int8_t cmmc_actuator_left_foil_feedback_power_encode(float value)
{
    return (int8_t)(value / 0.05f);
}

float cmmc_actuator_left_foil_feedback_power_decode(int8_t value)
{
    return ((float)value * 0.05f);
}

bool cmmc_actuator_left_foil_feedback_power_is_in_range(int8_t value)
{
    return ((value >= -120) && (value <= 120));
}

uint16_t cmmc_actuator_left_foil_feedback_setpoint_us_encode(float value)
{
    return (uint16_t)(value - 988.0f);
}

float cmmc_actuator_left_foil_feedback_setpoint_us_decode(uint16_t value)
{
    return ((float)value + 988.0f);
}

bool cmmc_actuator_left_foil_feedback_setpoint_us_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t cmmc_actuator_left_foil_feedback_position_raw_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_left_foil_feedback_position_raw_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_left_foil_feedback_position_raw_is_in_range(uint16_t value)
{
    return (value <= 4091u);
}

uint16_t cmmc_actuator_left_foil_feedback_free_bits_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_left_foil_feedback_free_bits_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_left_foil_feedback_free_bits_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t cmmc_actuator_left_foil_feedback_mode_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_actuator_left_foil_feedback_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_actuator_left_foil_feedback_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int cmmc_actuator_rear_foil_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_actuator_rear_foil_feedback_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current = (uint16_t)src_p->current;
    dst_p[0] |= pack_left_shift_u16(current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->voltage, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage, 6u, 0x0fu);
    power = (uint8_t)src_p->power;
    dst_p[2] |= pack_left_shift_u8(power, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u8(power, 4u, 0x0fu);
    dst_p[3] |= pack_left_shift_u16(src_p->setpoint_us, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->setpoint_us, 4u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->position_raw, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->position_raw, 2u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->position_raw, 10u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->free_bits, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->free_bits, 6u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->mode, 4u, 0xf0u);

    return (8);
}

int cmmc_actuator_rear_foil_feedback_unpack(
    struct cmmc_actuator_rear_foil_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((current & (1u << 9)) != 0u) {
        current |= 0xfc00u;
    }

    dst_p->current = (int16_t)current;
    dst_p->voltage = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    power = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    power |= unpack_left_shift_u8(src_p[3], 4u, 0x0fu);
    dst_p->power = (int8_t)power;
    dst_p->setpoint_us = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->setpoint_us |= unpack_left_shift_u16(src_p[4], 4u, 0x3fu);
    dst_p->position_raw = unpack_right_shift_u16(src_p[4], 6u, 0xc0u);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[6], 10u, 0x03u);
    dst_p->free_bits = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->free_bits |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);
    dst_p->mode = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);

    return (0);
}

int cmmc_actuator_rear_foil_feedback_init(struct cmmc_actuator_rear_foil_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_actuator_rear_foil_feedback_t));

    return 0;
}

int16_t cmmc_actuator_rear_foil_feedback_current_encode(float value)
{
    return (int16_t)(value / 0.002f);
}

float cmmc_actuator_rear_foil_feedback_current_decode(int16_t value)
{
    return ((float)value * 0.002f);
}

bool cmmc_actuator_rear_foil_feedback_current_is_in_range(int16_t value)
{
    return ((value >= -500) && (value <= 500));
}

uint16_t cmmc_actuator_rear_foil_feedback_voltage_encode(float value)
{
    return (uint16_t)((value - 3.6f) / 0.003f);
}

float cmmc_actuator_rear_foil_feedback_voltage_decode(uint16_t value)
{
    return (((float)value * 0.003f) + 3.6f);
}

bool cmmc_actuator_rear_foil_feedback_voltage_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

int8_t cmmc_actuator_rear_foil_feedback_power_encode(float value)
{
    return (int8_t)(value / 0.05f);
}

float cmmc_actuator_rear_foil_feedback_power_decode(int8_t value)
{
    return ((float)value * 0.05f);
}

bool cmmc_actuator_rear_foil_feedback_power_is_in_range(int8_t value)
{
    return ((value >= -120) && (value <= 120));
}

uint16_t cmmc_actuator_rear_foil_feedback_setpoint_us_encode(float value)
{
    return (uint16_t)(value - 988.0f);
}

float cmmc_actuator_rear_foil_feedback_setpoint_us_decode(uint16_t value)
{
    return ((float)value + 988.0f);
}

bool cmmc_actuator_rear_foil_feedback_setpoint_us_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t cmmc_actuator_rear_foil_feedback_position_raw_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_rear_foil_feedback_position_raw_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_rear_foil_feedback_position_raw_is_in_range(uint16_t value)
{
    return (value <= 4091u);
}

uint16_t cmmc_actuator_rear_foil_feedback_free_bits_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_rear_foil_feedback_free_bits_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_rear_foil_feedback_free_bits_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t cmmc_actuator_rear_foil_feedback_mode_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_actuator_rear_foil_feedback_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_actuator_rear_foil_feedback_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int cmmc_actuator_steering_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_actuator_steering_feedback_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current = (uint16_t)src_p->current;
    dst_p[0] |= pack_left_shift_u16(current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->voltage, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage, 6u, 0x0fu);
    power = (uint8_t)src_p->power;
    dst_p[2] |= pack_left_shift_u8(power, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u8(power, 4u, 0x0fu);
    dst_p[3] |= pack_left_shift_u16(src_p->setpoint_us, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->setpoint_us, 4u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->position_raw, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->position_raw, 2u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->position_raw, 10u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->free_bits, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->free_bits, 6u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->mode, 4u, 0xf0u);

    return (8);
}

int cmmc_actuator_steering_feedback_unpack(
    struct cmmc_actuator_steering_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current;
    uint8_t power;

    if (size < 8u) {
        return (-EINVAL);
    }

    current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((current & (1u << 9)) != 0u) {
        current |= 0xfc00u;
    }

    dst_p->current = (int16_t)current;
    dst_p->voltage = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    power = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    power |= unpack_left_shift_u8(src_p[3], 4u, 0x0fu);
    dst_p->power = (int8_t)power;
    dst_p->setpoint_us = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->setpoint_us |= unpack_left_shift_u16(src_p[4], 4u, 0x3fu);
    dst_p->position_raw = unpack_right_shift_u16(src_p[4], 6u, 0xc0u);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->position_raw |= unpack_left_shift_u16(src_p[6], 10u, 0x03u);
    dst_p->free_bits = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->free_bits |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);
    dst_p->mode = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);

    return (0);
}

int cmmc_actuator_steering_feedback_init(struct cmmc_actuator_steering_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_actuator_steering_feedback_t));

    return 0;
}

int16_t cmmc_actuator_steering_feedback_current_encode(float value)
{
    return (int16_t)(value / 0.002f);
}

float cmmc_actuator_steering_feedback_current_decode(int16_t value)
{
    return ((float)value * 0.002f);
}

bool cmmc_actuator_steering_feedback_current_is_in_range(int16_t value)
{
    return ((value >= -500) && (value <= 500));
}

uint16_t cmmc_actuator_steering_feedback_voltage_encode(float value)
{
    return (uint16_t)((value - 3.6f) / 0.003f);
}

float cmmc_actuator_steering_feedback_voltage_decode(uint16_t value)
{
    return (((float)value * 0.003f) + 3.6f);
}

bool cmmc_actuator_steering_feedback_voltage_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

int8_t cmmc_actuator_steering_feedback_power_encode(float value)
{
    return (int8_t)(value / 0.05f);
}

float cmmc_actuator_steering_feedback_power_decode(int8_t value)
{
    return ((float)value * 0.05f);
}

bool cmmc_actuator_steering_feedback_power_is_in_range(int8_t value)
{
    return ((value >= -120) && (value <= 120));
}

uint16_t cmmc_actuator_steering_feedback_setpoint_us_encode(float value)
{
    return (uint16_t)(value - 988.0f);
}

float cmmc_actuator_steering_feedback_setpoint_us_decode(uint16_t value)
{
    return ((float)value + 988.0f);
}

bool cmmc_actuator_steering_feedback_setpoint_us_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t cmmc_actuator_steering_feedback_position_raw_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_steering_feedback_position_raw_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_steering_feedback_position_raw_is_in_range(uint16_t value)
{
    return (value <= 4091u);
}

uint16_t cmmc_actuator_steering_feedback_free_bits_encode(float value)
{
    return (uint16_t)(value);
}

float cmmc_actuator_steering_feedback_free_bits_decode(uint16_t value)
{
    return ((float)value);
}

bool cmmc_actuator_steering_feedback_free_bits_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t cmmc_actuator_steering_feedback_mode_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_actuator_steering_feedback_mode_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_actuator_steering_feedback_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int cmmc_distance_fore_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_distance_fore_feedback_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->range_mm_l, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->error_status_l, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->signal_rate_mcps_l, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->signal_rate_mcps_l, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->range_mm_r, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->error_status_r, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->signal_rate_mcps_r, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->signal_rate_mcps_r, 8u, 0xffu);

    return (8);
}

int cmmc_distance_fore_feedback_unpack(
    struct cmmc_distance_fore_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->range_mm_l = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->error_status_l = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->signal_rate_mcps_l = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->signal_rate_mcps_l |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->range_mm_r = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->error_status_r = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->signal_rate_mcps_r = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->signal_rate_mcps_r |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int cmmc_distance_fore_feedback_init(struct cmmc_distance_fore_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_distance_fore_feedback_t));

    return 0;
}

uint8_t cmmc_distance_fore_feedback_range_mm_l_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_fore_feedback_range_mm_l_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_fore_feedback_range_mm_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_distance_fore_feedback_error_status_l_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_fore_feedback_error_status_l_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_fore_feedback_error_status_l_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint16_t cmmc_distance_fore_feedback_signal_rate_mcps_l_encode(float value)
{
    return (uint16_t)(value / 0.0078125f);
}

float cmmc_distance_fore_feedback_signal_rate_mcps_l_decode(uint16_t value)
{
    return ((float)value * 0.0078125f);
}

bool cmmc_distance_fore_feedback_signal_rate_mcps_l_is_in_range(uint16_t value)
{
    return (value <= 1280u);
}

uint8_t cmmc_distance_fore_feedback_range_mm_r_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_fore_feedback_range_mm_r_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_fore_feedback_range_mm_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_distance_fore_feedback_error_status_r_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_fore_feedback_error_status_r_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_fore_feedback_error_status_r_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint16_t cmmc_distance_fore_feedback_signal_rate_mcps_r_encode(float value)
{
    return (uint16_t)(value / 0.0078125f);
}

float cmmc_distance_fore_feedback_signal_rate_mcps_r_decode(uint16_t value)
{
    return ((float)value * 0.0078125f);
}

bool cmmc_distance_fore_feedback_signal_rate_mcps_r_is_in_range(uint16_t value)
{
    return (value <= 1280u);
}

int cmmc_distance_achter_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_distance_achter_feedback_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->range_mm_l, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->error_status_l, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->signal_rate_mcps_l, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->signal_rate_mcps_l, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->range_mm_r, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->error_status_r, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->signal_rate_mcps_r, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->signal_rate_mcps_r, 8u, 0xffu);

    return (8);
}

int cmmc_distance_achter_feedback_unpack(
    struct cmmc_distance_achter_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->range_mm_l = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->error_status_l = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->signal_rate_mcps_l = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->signal_rate_mcps_l |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->range_mm_r = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->error_status_r = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->signal_rate_mcps_r = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->signal_rate_mcps_r |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int cmmc_distance_achter_feedback_init(struct cmmc_distance_achter_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_distance_achter_feedback_t));

    return 0;
}

uint8_t cmmc_distance_achter_feedback_range_mm_l_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_achter_feedback_range_mm_l_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_achter_feedback_range_mm_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_distance_achter_feedback_error_status_l_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_achter_feedback_error_status_l_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_achter_feedback_error_status_l_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint16_t cmmc_distance_achter_feedback_signal_rate_mcps_l_encode(float value)
{
    return (uint16_t)(value / 0.0078125f);
}

float cmmc_distance_achter_feedback_signal_rate_mcps_l_decode(uint16_t value)
{
    return ((float)value * 0.0078125f);
}

bool cmmc_distance_achter_feedback_signal_rate_mcps_l_is_in_range(uint16_t value)
{
    return (value <= 1280u);
}

uint8_t cmmc_distance_achter_feedback_range_mm_r_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_achter_feedback_range_mm_r_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_achter_feedback_range_mm_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_distance_achter_feedback_error_status_r_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_achter_feedback_error_status_r_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_achter_feedback_error_status_r_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint16_t cmmc_distance_achter_feedback_signal_rate_mcps_r_encode(float value)
{
    return (uint16_t)(value / 0.0078125f);
}

float cmmc_distance_achter_feedback_signal_rate_mcps_r_decode(uint16_t value)
{
    return ((float)value * 0.0078125f);
}

bool cmmc_distance_achter_feedback_signal_rate_mcps_r_is_in_range(uint16_t value)
{
    return (value <= 1280u);
}

int cmmc_distance_bow_feedback_pack(
    uint8_t *dst_p,
    const struct cmmc_distance_bow_feedback_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->range_mm, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->error_status, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->signal_rate_mcps, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->signal_rate_mcps, 8u, 0xffu);

    return (4);
}

int cmmc_distance_bow_feedback_unpack(
    struct cmmc_distance_bow_feedback_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->range_mm = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->error_status = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->signal_rate_mcps = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->signal_rate_mcps |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int cmmc_distance_bow_feedback_init(struct cmmc_distance_bow_feedback_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_distance_bow_feedback_t));

    return 0;
}

uint8_t cmmc_distance_bow_feedback_range_mm_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_bow_feedback_range_mm_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_bow_feedback_range_mm_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_distance_bow_feedback_error_status_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_distance_bow_feedback_error_status_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_distance_bow_feedback_error_status_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint16_t cmmc_distance_bow_feedback_signal_rate_mcps_encode(float value)
{
    return (uint16_t)(value / 0.0078125f);
}

float cmmc_distance_bow_feedback_signal_rate_mcps_decode(uint16_t value)
{
    return ((float)value * 0.0078125f);
}

bool cmmc_distance_bow_feedback_signal_rate_mcps_is_in_range(uint16_t value)
{
    return (value <= 1280u);
}
