/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Fri Aug  8 18:44:19 2025.
 */

#include <string.h>

#include "cmmc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int cmmc_msg1_pack(
    uint8_t *dst_p,
    const struct cmmc_msg1_t *src_p,
    size_t size)
{
    uint8_t distance;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->speed, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->acceleration, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->acceleration, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->acceleration, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->acceleration, 24u, 0xffu);
    distance = (uint8_t)src_p->distance;
    dst_p[6] |= pack_left_shift_u8(distance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->status, 0u, 0xffu);

    return (8);
}

int cmmc_msg1_unpack(
    struct cmmc_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t distance;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->acceleration = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->acceleration |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->acceleration |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->acceleration |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    distance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->distance = (int8_t)distance;
    dst_p->status = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int cmmc_msg1_init(struct cmmc_msg1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_msg1_t));

    return 0;
}

uint16_t cmmc_msg1_speed_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float cmmc_msg1_speed_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool cmmc_msg1_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint32_t cmmc_msg1_acceleration_encode(float value)
{
    return (uint32_t)(value / 1e-06f);
}

float cmmc_msg1_acceleration_decode(uint32_t value)
{
    return ((float)value * 1e-06f);
}

bool cmmc_msg1_acceleration_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int8_t cmmc_msg1_distance_encode(float value)
{
    return (int8_t)(value);
}

float cmmc_msg1_distance_decode(int8_t value)
{
    return ((float)value);
}

bool cmmc_msg1_distance_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

uint8_t cmmc_msg1_status_encode(float value)
{
    return (uint8_t)(value);
}

float cmmc_msg1_status_decode(uint8_t value)
{
    return ((float)value);
}

bool cmmc_msg1_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int cmmc_msg2_pack(
    uint8_t *dst_p,
    const struct cmmc_msg2_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u32(src_p->somesignal, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->somesignal, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->somesignal, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->somesignal, 24u, 0xffu);

    return (4);
}

int cmmc_msg2_unpack(
    struct cmmc_msg2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->somesignal = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->somesignal |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->somesignal |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->somesignal |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

int cmmc_msg2_init(struct cmmc_msg2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct cmmc_msg2_t));

    return 0;
}

uint32_t cmmc_msg2_somesignal_encode(float value)
{
    return (uint32_t)(value);
}

float cmmc_msg2_somesignal_decode(uint32_t value)
{
    return ((float)value);
}

bool cmmc_msg2_somesignal_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}
